### ISSUE TITLE
Fix MinGW-w64/Clang `unknown-pragmas` warning.

### ISSUE THREAD

**Issue by CesarBerriot** [TinyTinni/ValveFileVDF#34]
### Recreation
`tree`
![Image](https://github.com/user-attachments/assets/c1ae32af-01f9-4f8a-8eea-ef4b9958b3dc)
`test.cpp`
```cpp
#include <vdf_parser.hpp>

int main(void) { return 0; }

```
`CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.30)
project(test CXX)

include(FetchContent)
FetchContent_Declare(ValveFileVDF GIT_REPOSITORY https://github.com/TinyTinni/ValveFileVDF.git GIT_TAG v1.1.0)
FetchContent_MakeAvailable(ValveFileVDF)

add_executable(test source/test.cpp)
target_link_libraries(test PRIVATE ValveFileVDF)
target_compile_options(test PRIVATE -Wall -Wextra)
```
### Result
`Configuration`
```
"C:\Program Files\JetBrains\CLion 2024.3.2\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_MAKE_PROGRAM=C:/Program Files/JetBrains/CLion 2024.3.2/bin/ninja/win/x64/ninja.exe" -G Ninja -S C:\Users\USERNAME\CLionProjects\test -B C:\Users\USERNAME\CLionProjects\test\cmake-build-debug
-- The CXX compiler identification is GNU 13.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/JetBrains/CLion 2024.3.2/bin/mingw/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Cloning into 'valvefilevdf-src'...
HEAD is now at 63176a3 adds some wchar_t proptests (#29)
-- The C compiler identification is GNU 13.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/JetBrains/CLion 2024.3.2/bin/mingw/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done (2.3s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/USERNAME/CLionProjects/test/cmake-build-debug

[Finished]
```
`Compilation`
```
====================[ Build | test | Debug ]====================================
"C:\Program Files\JetBrains\CLion 2024.3.2\bin\cmake\win\x64\bin\cmake.exe" --build C:\Users\USERNAME\CLionProjects\test\cmake-build-debug --target test -j 22
[1/2] Building CXX object CMakeFiles/test.dir/source/test.cpp.obj
In file included from C:/Users/USERNAME/CLionProjects/test/source/test.cpp:1:
C:/Users/USERNAME/CLionProjects/test/cmake-build-debug/_deps/valvefilevdf-src/include/vdf_parser.hpp:115: warning: ignoring '#pragma warning ' [-Wunknown-pragmas]
  115 | #pragma warning(push)
      | 
C:/Users/USERNAME/CLionProjects/test/cmake-build-debug/_deps/valvefilevdf-src/include/vdf_parser.hpp:116: warning: ignoring '#pragma warning ' [-Wunknown-pragmas]
  116 | #pragma warning(disable : 4996)
      | 
C:/Users/USERNAME/CLionProjects/test/cmake-build-debug/_deps/valvefilevdf-src/include/vdf_parser.hpp:122: warning: ignoring '#pragma warning ' [-Wunknown-pragmas]
  122 | #pragma warning(pop)
      | 
[2/2] Linking CXX executable test.exe

Build finished

```

**Comment by TinyTinni** [comment]
Hi,
thanks for the report.

The warnings should be fixed with https://github.com/TinyTinni/ValveFileVDF/issues/34

Can you test it? I don't have MinGW on windows at the moment.

**Comment by CesarBerriot** [comment]
I works 👍.

Although the following warnings are still present using `/Wall` on MSVC.
```
====================[ Build | test | Debug ]====================================
"C:\Program Files\JetBrains\CLion 2024.3.2\bin\cmake\win\x64\bin\cmake.exe" --build C:\Users\MichaelsoftBinbows\CLionProjects\test\cmake-build-debug --target test -j 22
[1/2] Building CXX object CMakeFiles\test.dir\source\test.cpp.obj
C:\Users\MichaelsoftBinbows\CLionProjects\test\cmake-build-debug\_deps\valvefilevdf-src\include\vdf_parser.hpp(93): warning C4514: 'tyti::vdf::detail::literal_macro_help<wchar_t>::result': unreferenced inline function has been removed
C:\Users\MichaelsoftBinbows\CLionProjects\test\cmake-build-debug\_deps\valvefilevdf-src\include\vdf_parser.hpp(98): warning C4514: 'tyti::vdf::detail::literal_macro_help<wchar_t>::result': unreferenced inline function has been removed
C:\Users\MichaelsoftBinbows\CLionProjects\test\cmake-build-debug\_deps\valvefilevdf-src\include\vdf_parser.hpp(106): warning C4514: 'tyti::vdf::detail::string_converter': unreferenced inline function has been removed
C:\Users\MichaelsoftBinbows\CLionProjects\test\cmake-build-debug\_deps\valvefilevdf-src\include\vdf_parser.hpp(108): warning C4514: 'tyti::vdf::detail::string_converter': unreferenced inline function has been removed
C:\Users\MichaelsoftBinbows\CLionProjects\test\cmake-build-debug\_deps\valvefilevdf-src\include\vdf_parser.hpp(238): warning C4514: 'tyti::vdf::Options::Options': unreferenced inline function has been removed
C:\Users\MichaelsoftBinbows\CLionProjects\test\cmake-build-debug\_deps\valvefilevdf-src\include\vdf_parser.hpp(248): warning C4514: 'tyti::vdf::WriteOptions::WriteOptions': unreferenced inline function has been removed
[2/2] Linking CXX executable test.exe

Build finished
```

**Comment by TinyTinni** [comment]
> I works 👍.

Great! I will merge it.

--------------

Regarding the other warnings for MSVC ([msdn link for C4514](https://learn.microsoft.com/sl-si/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4514?view=msvc-160)).

It looks like the compiler just informs, that those inline functions are not used in the final binary, which is true, because the library functions are not used by your executable.

In order to silence those warnings, I suspect you have to use the library. And just to make sure, you have to use every feature of the library so that your final binary uses every feature of it.

I don't think this is feasible, but from the library side, I don't see many options to silence the warnings.

Maybe, you should reconsider if you really want /Wall instead of /W4 on MSVC. /W4 seems to be recommended by MS

> "/W4 displays level 1, level 2, and level 3 warnings, and all level 4 (informational) warnings that aren't off by default. We recommend that you use this option to provide lint-like warnings. For a new project, it may be best to use /W4 in all compilations. This option helps ensure the fewest possible hard-to-find code defects."  [source](https://learn.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-170)

The STL gives warning free guarantees only for /W4

> "The C runtime libraries and the C++ standard libraries are intended to emit no warnings only at warning level [/W4](https://learn.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=msvc-170)." [source](https://learn.microsoft.com/en-us/cpp/preprocessor/compiler-warnings-that-are-off-by-default?view=msvc-170)

And that was the reason why I also just test on /W4 in the tests ([link](https://github.com/TinyTinni/ValveFileVDF/blob/master/tests/CMakeLists.txt#L13)).

The tests would also not recognize C4514 on these lines, because they use these functions.

**Comment by TinyTinni** [comment]
Issue was auto closed due to the merge event. Feel free to reopen/add another issue if you want to discuss C4514.
